include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    sort_child_properties_last: true
    directives_ordering: true
    avoid_relative_lib_imports: true
    sized_box_for_whitespace: true
    use_colored_box: true
    use_decorated_box: true
    avoid_unnecessary_containers: true
    omit_local_variable_types: true
    prefer_contains: true
    unnecessary_await_in_return: true
    unnecessary_parenthesis: true
    unnecessary_to_list_in_spreads: true
    use_build_context_synchronously: true
    use_to_and_as_if_applicable: true
    unnecessary_lambdas: true
    exhaustive_cases: true
    flutter_style_todos: true
    cascade_invocations: true
    avoid_redundant_argument_values: true
    always_use_package_imports: true
    use_rethrow_when_possible: true
    sort_unnamed_constructors_first: true
    tighten_type_of_initializing_formals: true
    prefer_iterable_whereType: true
    avoid_void_async: true
    await_only_futures: true
    avoid_escaping_inner_quotes: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
