name: bluecherry_client
description: Bluecherry client written in Flutter.

publish_to: "none"

version: 3.0.0-beta19

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  unity_video_player:
    path: packages/unity_video_player/unity_video_player/

  http: ^1.2.0
  # Dio is used by DownloadManager to show the donwload progress of the file. This is currently not possible by using http
  # TODO: no longer use dio and find a solution to show donwload progress using the http package
  dio: ^5.4.0

  xml2json: ^6.2.2
  auto_size_text: ^3.0.0
  animations: ^2.0.11
  provider: ^6.1.1
  reorderables: ^0.6.0
  flutter_simple_treeview: ^3.0.2
  sliver_tools: ^0.2.12

  intl: ^0.18.1
  flutter_localized_locales: ^2.0.5
  duration: ^4.0.3
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  awesome_notifications: ^0.9.3
  wakelock_plus: ^1.1.4
  app_links: ^6.3.2
  win32_registry: ^1.1.2
  
  # system_date_time_format: ^0.7.0
  device_info_plus: ^11.0.0
  package_info_plus: ^8.0.2
  connectivity_plus: ^6.0.5
  version: ^3.0.2
  url_launcher: ^6.2.4
  logging: ^1.2.0

  path_provider: ^2.1.2
  file_picker: ^8.1.2
  safe_local_storage: ^1.0.2 # This is required because media_kit is still locked to this version. When bumped in the upstream package, this can be removed
  
  permission_handler: ^11.1.0
  uuid: ^4.3.3

  # Desktop
  window_manager: ^0.4.2
  titlebar_buttons: ^1.0.0
  launch_at_startup: ^0.3.1
  # tray_manager: ^0.2.4
  unity_multi_window:
    path: packages/unity_multi_window/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  msix: ^3.7.0
  flutter_launcher_icons: ^0.14.1

dependency_overrides:
  intl: 0.18.1

flutter:
  uses-material-design: true
  # The following line ensures that the translations are generated before the
  # application build using the ARB files provided.
  generate: true
  assets:
    - assets/images/

flutter_icons:
  # android: "launcher_icon"
  android: false
  ios: false
  image_path: "assets/images/icon.png"
  # min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#3F51B5"
    theme_color: "#ff4081"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"

msix_config:
  display_name: Bluecherry Client
  publisher_display_name: Bluecherry DVR
  identity_name: bluecherry.dvr.unity
  # msix_version: 1.0.0.0
  logo_path: assets\images\icon.png
  capabilities: internetClient
