name: unity_video_player_mobile
description: Unity Video Player implementation for iOS and Android
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fijkplayer:
    git:
      # Fixes the bad memory access on iOS, upon application quit from the App Switcher.
      url: https://github.com/bdlukaa/fijkplayer.git
      ref: master
  unity_video_player_platform_interface:
    path: ../unity_video_player_platform_interface/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: unity_video_player
    platforms:
      android:
        dartPluginClass: UnityVideoPlayerMobileInterface
      ios:
        dartPluginClass: UnityVideoPlayerMobileInterface