name: unity_video_player_main
description: UnityVideoPlayer implemented using MediaKit
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  media_kit: ^1.1.6                              # Primary package.
  media_kit_video: ^1.1.7                        # For video rendering.
  media_kit_libs_video: ^1.0.0                   # Native video dependencies.
  unity_video_player_platform_interface:
    path: ../unity_video_player_platform_interface/
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: unity_video_player
    platforms:
      windows:
        dartPluginClass: UnityVideoPlayerMediaKitInterface
      linux:
        dartPluginClass: UnityVideoPlayerMediaKitInterface
      macos:
        dartPluginClass: UnityVideoPlayerMediaKitInterface
      ios:
        dartPluginClass: UnityVideoPlayerMediaKitInterface
      android:
        dartPluginClass: UnityVideoPlayerMediaKitInterface
