name: unity_video_player_fvp
description: "Implements MDK Unity Video Player for Flutter"
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  unity_video_player_platform_interface:
    path: ../unity_video_player_platform_interface/
  fvp: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  plugin:
    implements: unity_video_player
    platforms:
      windows:
        dartPluginClass: UnityVideoPlayerFvpInterface
      linux:
        dartPluginClass: UnityVideoPlayerFvpInterface
      # macos:
      #   dartPluginClass: UnityVideoPlayerFvpInterface
      # ios:
      #   dartPluginClass: UnityVideoPlayerFvpInterface
      # android:
      #   dartPluginClass: UnityVideoPlayerFvpInterface
      # web:
      #   pluginClass: UnityVideoPlayerFvpInterface
      #   fileName: unity_video_player_main.dart