name: bluecherry-client
version: '3.0.0'
summary: Bluecherry DVR Client
description: |
  The client app for Bluecherry to view live-streams and events of your cameras.

base: core22
confinement: strict
grade: stable

apps:
  bluecherry-client:
    command: bluecherry_client
    extensions: [gnome]

parts:
  bluecherry-client:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart

    build-packages:
      - curl # This appears to be needed when building in the Snap Store.
      - libsecret-1-dev
      - libjsoncpp-dev

    stage-packages:
      - libsecret-1-0
      - libjsoncpp-dev

architectures:
  - build-on: [ amd64 ]
  - build-on: [ arm64 ]